/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwaregenerador;

import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
public class dglGenerador extends javax.swing.JDialog {

    /**
     * Creates new form dglGenerador
     */
    public dglGenerador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model  = (DefaultTableModel) this.tblDatos.getModel();
    }
 
    ArrayList<String> lista = new ArrayList();
    ArrayList<Double> listaDo = new ArrayList();
    ArrayList<Integer> bits = new ArrayList();
    DefaultTableModel model;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        JcbConfiabilidad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfZ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        txtfCo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfMedia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfVarianza = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfZo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaSerie = new javax.swing.JTextArea();
        Resultado = new javax.swing.JLabel();
        Nota = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAbrir.setBackground(new java.awt.Color(0, 255, 204));
        btnAbrir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAbrir.setText("ABRIR ARCHIVO");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        tblDatos.setBackground(new java.awt.Color(51, 255, 255));
        tblDatos.setBorder(new javax.swing.border.MatteBorder(null));
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Datos"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 375, 168));

        JcbConfiabilidad.setBackground(new java.awt.Color(204, 255, 204));
        JcbConfiabilidad.setEditable(true);
        JcbConfiabilidad.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        JcbConfiabilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "90%", "95%", "99%" }));
        JcbConfiabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbConfiabilidadActionPerformed(evt);
            }
        });
        getContentPane().add(JcbConfiabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 61, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel1.setText("Confiabilidad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Corridas =");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 51, 255));
        jLabel3.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jLabel3.setText("Prueba de Corridas Arriba y abajo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 25));

        txtfZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfZActionPerformed(evt);
            }
        });
        getContentPane().add(txtfZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 61, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Z = ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 34, 20));

        btnCalcular.setBackground(new java.awt.Color(51, 255, 204));
        btnCalcular.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnCalcular.setText("Calculos");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));
        getContentPane().add(txtfCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 126, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Media =");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));
        getContentPane().add(txtfMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Varianza =");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));
        getContentPane().add(txtfVarianza, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 125, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Zo =");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, -1));
        getContentPane().add(txtfZo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Serie");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        txtaSerie.setColumns(20);
        txtaSerie.setRows(5);
        jScrollPane2.setViewportView(txtaSerie);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 375, 36));

        Resultado.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 420, 80));

        Nota.setBackground(new java.awt.Color(0, 255, 153));
        Nota.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        Nota.setText("Nota");
        Nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotaActionPerformed(evt);
            }
        });
        getContentPane().add(Nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondogebe3.jpg"))); // NOI18N
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        String aux="", Primer;
        try{

            JFileChooser file = new JFileChooser();
            file.showOpenDialog(this);
            File abre = file.getSelectedFile();
            aux = abre.getPath();
        }catch(Exception x){
            JOptionPane.showMessageDialog(null, "Error : " + x.toString());
        }
        
        Scanner linea = null;
        lista.clear();
        File doc_le = new File(aux);

        try{
            linea = new Scanner(doc_le);
            while(linea.hasNext()){
                listaDo.add(linea.nextDouble());             
            }
            
           
            
        }catch(Exception x){
            JOptionPane.showMessageDialog(null, "Error : " + x.toString() );
        }
        
        try{
            linea = new Scanner(doc_le);
            
            while(linea.hasNext()){
                lista.add(linea.nextLine());  
                Primer =linea.next();
                model.addRow(new Object[]{Primer});
            }
           
            
        }catch(Exception x){
            JOptionPane.showMessageDialog(null, "Error : " + x.toString() );
        }

    }//GEN-LAST:event_btnAbrirActionPerformed

    private void JcbConfiabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbConfiabilidadActionPerformed

       if(JcbConfiabilidad.getSelectedItem() == "90%"){
         txtfZ.setText("1.96");
       }else if(JcbConfiabilidad.getSelectedItem() == "95%"){
         txtfZ.setText("1.64");  
       }else if(JcbConfiabilidad.getSelectedItem() == "99%"){
         txtfZ.setText("2.58");  
       }
      
    }//GEN-LAST:event_JcbConfiabilidadActionPerformed

    private void txtfZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfZActionPerformed
         
    }//GEN-LAST:event_txtfZActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double Confia = Double.parseDouble(this.txtfZ.getText().trim());
        int i, corridas, valor;
        double media, varianza, Z;
        
        for (i = 1; i < listaDo.size(); i ++) {
            if (listaDo.get(i) <= listaDo.get(i-1)) {
                bits.add(0);
            }else{
                bits.add(1);
            }
        }
        
        txtaSerie.setText(bits.toString());
     
        corridas = 1;
        valor = bits.get(0);
        
        for (i = 1; i < bits.size(); i++) {
            if (bits.get(i) != valor) {
                corridas++;
                valor = bits.get(i);
            }
        }
        txtfCo.setText(String.valueOf(corridas));
        media = (2*listaDo.size()-1)/(double)3;
        txtfMedia.setText(String.valueOf(media));
        varianza = (16*listaDo.size()-29)/(double)90;
        txtfVarianza.setText(String.valueOf(varianza));
        Z = Math.abs((corridas - media)/Math.sqrt(varianza));
        txtfZo.setText(String.valueOf(Z));

        
       try{
           
           if (Z < Confia) {
               Resultado.setText("se concluye que no se puede rechazar que los números del conjunto r¡");
           }else{
               Resultado.setText("No Pasa la prueba de corridas");
           }    
       }catch(Exception x){
           JOptionPane.showMessageDialog(null, "Seleccione el nivel de Confiablidad");
       }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void NotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaActionPerformed
        JOptionPane.showMessageDialog(null, "Se recomienda cerrar esta venta y volverla "
                + "a abrir para la proxima prueba");
    }//GEN-LAST:event_NotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dglGenerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dglGenerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dglGenerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dglGenerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dglGenerador dialog = new dglGenerador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbConfiabilidad;
    private javax.swing.JButton Nota;
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextArea txtaSerie;
    private javax.swing.JTextField txtfCo;
    private javax.swing.JTextField txtfMedia;
    private javax.swing.JTextField txtfVarianza;
    private javax.swing.JTextField txtfZ;
    private javax.swing.JTextField txtfZo;
    // End of variables declaration//GEN-END:variables
}
